"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { calculateScenario, calculateScenarioDifference } from "@/buying-power/calculations";
import type { BuyingPowerScenarioInput, BuyingPowerSharedAssumptions } from "@/buying-power/types";

const usd = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 });
const signed = (n: number, suffix = "") => `${n >= 0 ? "+" : "−"}${usd.format(Math.abs(n))}${suffix}`;
const initialShared: BuyingPowerSharedAssumptions = { borrowerName: "", loanProgram: "conventional", termYears: 30, interestRate: 6.5, apr: 6.72, downPaymentPercent: 5, annualPropertyTaxes: 3600, annualHomeownersInsurance: 1800, monthlyMortgageInsurance: 90, monthlyHoa: 75, closingCosts: 9000, sellerConcessions: 0, discountPointsPercent: 0, lenderCredits: 0, prepaidEscrows: 2500, targetMonthlyPayment: null, holdingPeriodYears: 5 };
const makeScenarios = (base = 460000, increment = 10000): BuyingPowerScenarioInput[] => [0, 1, 2].map((i) => ({ id: String.fromCharCode(97 + i), name: `Scenario ${String.fromCharCode(65 + i)}`, purchasePrice: base + increment * i, notes: "", overrides: {} }));

export default function BuyingPowerPage() {
  const [shared, setShared] = useState(initialShared); const [base, setBase] = useState(460000); const [increment, setIncrement] = useState(10000);
  const [scenarios, setScenarios] = useState(makeScenarios()); const [manualPrices, setManualPrices] = useState(false); const [view, setView] = useState<"input" | "report">("input"); const [advanced, setAdvanced] = useState(false);
  useEffect(() => { const raw = localStorage.getItem("bhl-buying-power"); if (raw) try { const d = JSON.parse(raw); setShared(d.shared); setScenarios(d.scenarios); setBase(d.base); setIncrement(d.increment); } catch {} }, []);
  const results = useMemo(() => scenarios.map((s) => calculateScenario(s, shared)), [scenarios, shared]);
  const differences = useMemo(() => results.slice(1).map((r, i) => calculateScenarioDifference(r, results[i])), [results]);
  const changeShared = (key: keyof BuyingPowerSharedAssumptions, value: string) => setShared((s) => ({ ...s, [key]: key === "borrowerName" || key === "loanProgram" ? value : key === "targetMonthlyPayment" && value === "" ? null : Number(value) } as BuyingPowerSharedAssumptions));
  const changeScenario = (index: number, key: "name" | "purchasePrice" | "notes", value: string) => setScenarios((all) => all.map((s, i) => i === index ? { ...s, [key]: key === "purchasePrice" ? Number(value) : value } : s));
  const changeOverride = (index: number, key: keyof BuyingPowerScenarioInput["overrides"], value: string) => setScenarios((all) => all.map((s, i) => i === index ? { ...s, overrides: { ...s.overrides, [key]: value === "" ? undefined : Number(value) } } : s));
  const generatePrices = () => setScenarios((all) => all.map((s, i) => ({ ...s, purchasePrice: base + increment * i })));
  const save = () => localStorage.setItem("bhl-buying-power", JSON.stringify({ shared, scenarios, base, increment }));

  return <main className="bp-page">
    <header className="app-header no-print"><Link className="brand" href="/"><span className="brand-mark">B</span><span>Bacon Home Loans<small>Buying Power Studio</small></span></Link><div className="header-actions"><button className="button ghost" onClick={save}>Save comparison</button>{view === "report" && <button className="button primary" onClick={() => window.print()}>Export PDF</button>}</div></header>
    {view === "input" ? <div className="bp-workspace"><aside className="bp-intro"><span className="eyebrow">Buying power</span><h1>What does another home price change?</h1><p>Set the loan once. Compare three prices in under a minute.</p><div className="bp-live"><span>Current range</span><strong>{usd.format(scenarios[0].purchasePrice)} — {usd.format(scenarios[2].purchasePrice)}</strong><small>{shared.downPaymentPercent}% down · {shared.interestRate}% · {shared.termYears} years</small></div></aside>
      <section className="bp-form"><div className="bp-form-head"><div><span className="eyebrow">New comparison</span><h2>Build three scenarios</h2></div><span className="bp-step">Manual estimates</span></div>
        <section className="bp-input-section"><h3><b>01</b> Purchase prices</h3><div className="bp-mode"><button className={!manualPrices ? "on" : ""} onClick={() => setManualPrices(false)}>Base + increment</button><button className={manualPrices ? "on" : ""} onClick={() => setManualPrices(true)}>Enter individually</button></div>{!manualPrices ? <div className="bp-grid three"><Money label="Base purchase price" value={base} onChange={setBase}/><Money label="Price increment" value={increment} onChange={setIncrement}/><button className="bp-generate" onClick={generatePrices}>Generate prices</button></div> : null}<div className="bp-scenario-inputs">{scenarios.map((s, i) => <div key={s.id}><input className="bp-name" value={s.name} onChange={(e) => changeScenario(i, "name", e.target.value)}/><Money label={`Price ${String.fromCharCode(65 + i)}`} value={s.purchasePrice} onChange={(v) => changeScenario(i, "purchasePrice", String(v))}/></div>)}</div></section>
        <section className="bp-input-section"><h3><b>02</b> Loan</h3><div className="bp-grid four"><Field label="Borrower (optional)"><input value={shared.borrowerName} onChange={(e) => changeShared("borrowerName", e.target.value)} placeholder="Client name"/></Field><Field label="Loan program"><select value={shared.loanProgram} onChange={(e) => changeShared("loanProgram", e.target.value)}><option value="conventional">Conventional</option><option value="fha">FHA</option><option value="va">VA</option><option value="usda">USDA</option><option value="other">Other</option></select></Field><NumberField label="Down payment" suffix="%" value={shared.downPaymentPercent} onChange={(v) => changeShared("downPaymentPercent", v)} /><NumberField label="Interest rate" suffix="%" step="0.125" value={shared.interestRate} onChange={(v) => changeShared("interestRate", v)} /><NumberField label="APR" suffix="%" step="0.01" value={shared.apr ?? 0} onChange={(v) => changeShared("apr", v)} /><Field label="Loan term"><select value={shared.termYears} onChange={(e) => changeShared("termYears", e.target.value)}><option value="30">30 years</option><option value="20">20 years</option><option value="15">15 years</option></select></Field><Money label="Target payment (optional)" value={shared.targetMonthlyPayment ?? 0} blank onChange={(v) => changeShared("targetMonthlyPayment", v ? String(v) : "")}/></div></section>
        <section className="bp-input-section"><h3><b>03</b> Monthly housing costs</h3><div className="bp-grid four"><Money label="Annual property taxes" value={shared.annualPropertyTaxes} onChange={(v) => changeShared("annualPropertyTaxes", String(v))}/><Money label="Annual homeowners insurance" value={shared.annualHomeownersInsurance} onChange={(v) => changeShared("annualHomeownersInsurance", String(v))}/><Money label="Monthly mortgage insurance" value={shared.monthlyMortgageInsurance} onChange={(v) => changeShared("monthlyMortgageInsurance", String(v))}/><Money label="Monthly HOA" value={shared.monthlyHoa} onChange={(v) => changeShared("monthlyHoa", String(v))}/></div></section>
        <section className="bp-input-section"><button className="bp-disclosure-button" onClick={() => setAdvanced(!advanced)}><span><b>04</b> Closing costs & advanced options</span><span>{advanced ? "−" : "+"}</span></button>{advanced && <><div className="bp-grid four bp-advanced"><Money label="Closing costs" value={shared.closingCosts} onChange={(v) => changeShared("closingCosts", String(v))}/><Money label="Prepaids & escrows" value={shared.prepaidEscrows} onChange={(v) => changeShared("prepaidEscrows", String(v))}/><Money label="Seller concessions" value={shared.sellerConcessions} onChange={(v) => changeShared("sellerConcessions", String(v))}/><Money label="Lender credits" value={shared.lenderCredits} onChange={(v) => changeShared("lenderCredits", String(v))}/><NumberField label="Discount points" suffix="%" step="0.125" value={shared.discountPointsPercent} onChange={(v) => changeShared("discountPointsPercent", v)}/></div><div className="bp-overrides"><span>Scenario-specific overrides</span>{scenarios.map((s, i) => <details key={s.id}><summary>{s.name}<small>Optional rate, costs, and credits</small></summary><div className="bp-grid four"><NumberField label="Rate override" suffix="%" blank value={s.overrides.interestRate ?? 0} onChange={(v) => changeOverride(i, "interestRate", v)}/><Money label="Down payment amount" blank value={s.overrides.downPaymentAmount ?? 0} onChange={(v) => changeOverride(i, "downPaymentAmount", String(v || ""))}/><Money label="Closing costs" blank value={s.overrides.closingCosts ?? 0} onChange={(v) => changeOverride(i, "closingCosts", String(v || ""))}/><Money label="Seller concessions" blank value={s.overrides.sellerConcessions ?? 0} onChange={(v) => changeOverride(i, "sellerConcessions", String(v || ""))}/></div></details>)}</div></>}</section>
        <div className="bp-submit"><div><span>Starting estimated payment</span><strong>{usd.format(results[0].totalMonthlyHousingPayment)}<small>/mo</small></strong></div><button className="button primary large" onClick={() => { save(); setView("report"); }}>Create client comparison →</button></div>
      </section></div> : <BuyingPowerReport shared={shared} results={results} differences={differences} onEdit={() => setView("input")}/>}</main>;
}

function BuyingPowerReport({ shared, results, differences, onEdit }: { shared: BuyingPowerSharedAssumptions; results: ReturnType<typeof calculateScenario>[]; differences: ReturnType<typeof calculateScenarioDifference>[]; onEdit: () => void }) {
  return <div className="bp-report-wrap"><div className="report-toolbar no-print"><button className="text-button" onClick={onEdit}>← Edit comparison</button><span>Client presentation · API-free estimates</span></div><article className="bp-report">
    <header className="bp-report-hero"><div className="report-brand"><span className="brand-mark light">B</span><div>Bacon Home Loans<small>Home buying power comparison</small></div></div><span>Prepared {new Date().toLocaleDateString()}</span><div><p>{shared.borrowerName ? `Prepared for ${shared.borrowerName}` : "Purchase price comparison"}</p><h1>See what each price point changes.</h1><h2>Monthly payment and upfront cost estimates, side by side.</h2></div></header>
    <section className="bp-cards">{results.map((r, i) => <div className={i === 1 ? "bp-card featured" : "bp-card"} key={r.id}><span className="bp-card-name">{r.name}</span><h3>{usd.format(r.purchasePrice)}</h3><div className="bp-big-metric"><span>Estimated payment</span><strong>{usd.format(r.totalMonthlyHousingPayment)}<small>/mo</small></strong>{i > 0 && <em>{signed(r.totalMonthlyHousingPayment - results[0].totalMonthlyHousingPayment)}/mo from base</em>}</div><div className="bp-cash"><span>Estimated cash to close</span><strong>{usd.format(r.cashToClose)}</strong>{i > 0 && <em>{signed(r.cashToClose - results[0].cashToClose)} from base</em>}</div>{r.targetPaymentDifference !== null && <div className={r.targetPaymentDifference <= 0 ? "bp-target under" : "bp-target"}>{usd.format(Math.abs(r.targetPaymentDifference))} {r.targetPaymentDifference <= 0 ? "below" : "above"} selected target</div>}</div>)}</section>
    <section className="bp-report-section bp-tradeoffs"><div className="eyebrow">The practical difference</div><h2>{differences.every((d) => d.purchasePrice === differences[0].purchasePrice) ? `What does another ${usd.format(differences[0].purchasePrice)} cost?` : "What does each next price point cost?"}</h2><div className="bp-trade-grid">{differences.map((d, i) => <div key={i}><span>{usd.format(results[i].purchasePrice)} <b>→</b> {usd.format(results[i + 1].purchasePrice)}</span><strong>{signed(d.monthlyPayment)}<small>/month</small></strong><p>{signed(d.cashToClose)} estimated cash to close</p><p>{signed(d.loanAmount)} added to the loan amount</p></div>)}</div><p className="bp-question">Is the additional home worth the additional monthly and upfront cost? That decision is yours—the purpose of this comparison is to make the tradeoff visible.</p></section>
    <section className="bp-report-section"><div className="eyebrow">Monthly payment</div><h2>What makes up each estimate</h2><Comparison rows={["Principal & interest","Property taxes","Homeowners insurance","Mortgage insurance","HOA","Total housing payment"]} results={results} values={(r) => [r.monthlyPrincipalAndInterest,r.monthlyTaxes,r.monthlyInsurance,r.monthlyMortgageInsurance,r.monthlyHoa,r.totalMonthlyHousingPayment]}/></section>
    <section className="bp-report-section alt"><div className="eyebrow">Upfront costs</div><h2>Estimated cash to close</h2><Comparison rows={["Down payment","Closing costs","Prepaids & escrows","Discount points","Less seller concessions","Less lender credits","Estimated cash to close"]} results={results} values={(r) => [r.downPayment,r.closingCosts,r.prepaidEscrows,r.discountPoints,-r.sellerConcessions,-r.lenderCredits,r.cashToClose]}/>{results.some((r) => r.potentialUnusedSellerCredit > 0) && <div className="bp-warning">Potential unused seller credit. Verify allowable application based on loan program and lender guidelines.</div>}</section>
    <details className="bp-longterm"><summary>Optional {shared.holdingPeriodYears}-year loan snapshot <span>Show details +</span></summary><div className="bp-report-section"><Comparison rows={["Estimated principal paid","Estimated interest paid","Estimated remaining balance"]} results={results} values={(r) => [r.principalPaidAtHoldingPeriod,r.interestPaidAtHoldingPeriod,r.remainingBalanceAtHoldingPeriod]}/></div></details>
    <section className="bp-report-section bp-assumptions"><div><div className="eyebrow">Shared assumptions</div><h2>The inputs behind this comparison</h2></div><div className="bp-assumption-list"><span>Loan program<strong>{shared.loanProgram}</strong></span><span>Term<strong>{shared.termYears} years</strong></span><span>Rate<strong>{shared.interestRate}%</strong></span><span>APR<strong>{shared.apr ?? "N/A"}%</strong></span><span>Down payment<strong>{shared.downPaymentPercent}%</strong></span><span>Input status<strong>Manual estimate</strong></span></div></section>
    <section className="bp-internal no-print"><div><div className="eyebrow">Loan officer view</div><h2>Technical snapshot</h2></div>{results.map((r) => <div key={r.id}><b>{r.name}</b><span>LTV {r.ltvPercent}%</span><span>Loan {usd.format(r.loanAmount)}</span><span>P&amp;I {usd.format(r.monthlyPrincipalAndInterest)}</span><span>APR {r.apr ?? "N/A"}%</span></div>)}</section>
    <footer className="disclosure"><strong>Important disclosure</strong><p>All figures shown are estimates for educational and comparison purposes only. Actual interest rates, APR, payment, taxes, insurance, mortgage insurance, closing costs, cash to close, loan eligibility, and other terms may vary based on the final property, borrower qualifications, market conditions, loan program, lender requirements, and verified documentation. This comparison is not a commitment to lend or guarantee of approval.</p><div><span>Austin Bacon · Bacon Home Loans</span><span>Artemis Mortgage · Arizona</span><span>For compliance review before publication</span></div></footer>
  </article></div>;
}
function Comparison({ rows, results, values }: { rows: string[]; results: ReturnType<typeof calculateScenario>[]; values: (r: ReturnType<typeof calculateScenario>) => number[] }) { return <div className="bp-comparison"><div className="bp-table-head"><span></span>{results.map((r) => <strong key={r.id}>{r.name}<small>{usd.format(r.purchasePrice)}</small></strong>)}</div>{rows.map((row, i) => <div className={i === rows.length - 1 ? "total" : ""} key={row}><span>{row}</span>{results.map((r) => <strong key={r.id}>{usd.format(values(r)[i])}</strong>)}</div>)}</div>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="bp-field"><span>{label}</span>{children}</label>; }
function Money({ label, value, onChange, blank = false }: { label: string; value: number; onChange: (v: number) => void; blank?: boolean }) { return <Field label={label}><div className="bp-money"><span>$</span><input type="number" min="0" value={blank && value === 0 ? "" : value} placeholder={blank ? "Optional" : "0"} onChange={(e) => onChange(Number(e.target.value))}/></div></Field>; }
function NumberField({ label, value, onChange, suffix, step = "1", blank = false }: { label: string; value: number; onChange: (v: string) => void; suffix: string; step?: string; blank?: boolean }) { return <Field label={label}><div className="bp-number"><input type="number" min="0" step={step} value={blank && value === 0 ? "" : value} placeholder={blank ? "Optional" : "0"} onChange={(e) => onChange(e.target.value)}/><span>{suffix}</span></div></Field>; }
