"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { calculateScenario, calculateScenarioDifference, formatPercent } from "@/buying-power/calculations";
import { validateClientExport } from "@/buying-power/compliance";
import { BUYING_POWER_STORAGE_KEY, BUYING_POWER_STORAGE_VERSION, migrateBuyingPowerState, scenariosForMode } from "@/buying-power/storage";
import type { ApprovalRecord, BuyingPowerScenarioInput, BuyingPowerSharedAssumptions, DisclosureConfig, PaymentInclusions, ReportStatus, ScenarioOverrides } from "@/buying-power/types";

const usd = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 });
const initialShared: BuyingPowerSharedAssumptions = { borrowerName: "", loanProgram: "conventional", termYears: 30, defaultInterestRate: 0, defaultDownPaymentPercent: 0, annualPropertyTaxes: 0, annualHomeownersInsurance: 0, defaultMonthlyMortgageInsurance: 0, monthlyHoa: 0, defaultClosingCosts: 0, defaultSellerConcessions: 0, defaultDiscountPointsPercent: 0, defaultLenderCredits: 0, prepaidEscrows: 0, earnestMoneyDeposit: null, targetMonthlyPayment: null, holdingPeriodYears: 5 };
const makeScenarios = (base = 0, mode: "price" | "downPayment" = "price"): BuyingPowerScenarioInput[] => [0, 1, 2].map((i) => ({ id: String.fromCharCode(97 + i), name: mode === "price" ? `Scenario ${String.fromCharCode(65 + i)}` : `${[5,10,20][i]}% Down`, purchasePrice: mode === "price" ? base + i * 10000 : base, notes: "", overrides: mode === "downPayment" ? { downPaymentPercent: [5,10,20][i] } : {} }));
const initialDisclosure: DisclosureConfig = { loanOfficerName: "Austin Bacon", loanOfficerTitle: "Mortgage Loan Originator", loanOfficerNmlsId: "2728600", companyName: "Artemis Mortgage", companyNmlsId: "", companyState: "Arizona", companyLicenseType: "", companyStateLicenseNumber: "", customDisclosure: "" };
const initialInclusions: PaymentInclusions = { propertyTaxes: true, homeownersInsurance: true, mortgageInsurance: true, hoa: true };
const initialApproval: ApprovalRecord = { approvalConfirmed: false, approvedBy: "", approvedAt: "", approvalReference: "" };

export default function BuyingPowerPage() {
  const [shared,setShared]=useState(initialShared); const [scenarios,setScenarios]=useState(makeScenarios()); const [mode,setMode]=useState<"price"|"downPayment">("price"); const [base,setBase]=useState(0); const [increment,setIncrement]=useState(10000); const [view,setView]=useState<"input"|"report">("input");
  const [disclosure,setDisclosure]=useState(initialDisclosure); const [inclusions,setInclusions]=useState(initialInclusions); const [status,setStatus]=useState<ReportStatus>("draft"); const [rateAsOf,setRateAsOf]=useState(""); const [approval,setApproval]=useState(initialApproval);
  const defaults={shared:initialShared,scenarios:makeScenarios(),base:0,increment:10000,compareMode:"price" as const,disclosure:initialDisclosure,inclusions:initialInclusions,reportStatus:"draft" as const,rateAsOf:"",approval:initialApproval};
  useEffect(()=>{const raw=localStorage.getItem(BUYING_POWER_STORAGE_KEY);if(raw)try{const d=migrateBuyingPowerState(JSON.parse(raw),defaults);setShared(d.shared);setScenarios(d.scenarios);setBase(d.base);setIncrement(d.increment);setMode(d.compareMode);setDisclosure(d.disclosure);setInclusions(d.inclusions);setStatus(d.reportStatus);setRateAsOf(d.rateAsOf);setApproval(d.approval);}catch{}},[]);
  const results=useMemo(()=>scenarios.map(s=>calculateScenario(s,shared,inclusions)),[scenarios,shared,inclusions]); const differences=useMemo(()=>results.slice(1).map(r=>calculateScenarioDifference(r,results[0])),[results]); const compliance=useMemo(()=>validateClientExport(disclosure,approval,shared,results,inclusions,rateAsOf),[disclosure,approval,shared,results,inclusions,rateAsOf]);
  const setSharedValue=(key:keyof BuyingPowerSharedAssumptions,value:string)=>setShared(s=>({...s,[key]:key==="borrowerName"||key==="loanProgram"?value:(key==="earnestMoneyDeposit"||key==="targetMonthlyPayment")&&value===""?null:Number(value)} as BuyingPowerSharedAssumptions));
  const setOverride=(i:number,key:keyof ScenarioOverrides,value:string)=>setScenarios(all=>all.map((s,n)=>n===i?{...s,overrides:{...s.overrides,[key]:value===""?undefined:Number(value)}}:s));
  const switchMode=(next:typeof mode)=>{setMode(next);setStatus("draft");setApproval(initialApproval);setScenarios(scenariosForMode(base,next));};
  const save=()=>localStorage.setItem(BUYING_POWER_STORAGE_KEY,JSON.stringify({version:BUYING_POWER_STORAGE_VERSION,shared,scenarios,base,increment,compareMode:mode,disclosure,inclusions,reportStatus:status,rateAsOf,approval}));
  const exportAllowed=status==="approved"&&compliance.valid;
  return <main className="bp-page"><header className="app-header no-print"><Link className="brand" href="/"><span className="brand-mark">A</span><span>Artemis Mortgage<small>Buying Power Studio</small></span></Link><div className="header-actions"><button className="button ghost" onClick={save}>Save comparison</button>{view==="report"&&<button className="button primary" disabled={!exportAllowed} onClick={()=>window.print()}>Export PDF</button>}</div></header>
  {view==="input"?<div className="bp-workspace"><aside className="bp-intro"><span className="eyebrow">Buying power</span><h1>{mode==="price"?"What does another home price change?":"What does putting more down change?"}</h1><p>Manual comparison workspace. Blank values are unknown; zero means confirmed zero.</p><div className="bp-live"><span>{mode==="price"?"Current range":"Selected property"}</span><strong>{mode==="price"?`${usd.format(scenarios[0].purchasePrice)} — ${usd.format(scenarios[2].purchasePrice)}`:usd.format(base)}</strong><small>{mode==="price"?`${formatPercent(shared.defaultDownPaymentPercent)} down`:`${scenarios.map(s=>formatPercent(s.overrides.downPaymentPercent??0)).join(" · ")} down`} · {formatPercent(shared.defaultInterestRate)} default rate · {shared.termYears} years</small></div></aside>
  <section className="bp-form"><div className="bp-form-head"><div><span className="eyebrow">New comparison</span><h2>Build three scenarios</h2></div><span className="bp-step">Manual estimates</span></div>
  <Section n="01" title="Choose what to compare"><div className="bp-compare-mode"><button className={mode==="price"?"on":""} onClick={()=>switchMode("price")}><strong>Purchase price</strong><span>Compare three prices</span></button><button className={mode==="downPayment"?"on":""} onClick={()=>switchMode("downPayment")}><strong>Down payment</strong><span>Compare cash, payment, and MI</span></button></div></Section>
  <Section n="02" title={mode==="price"?"Purchase-price scenarios":"Property & down-payment scenarios"}><div className="bp-grid three"><Money label="Property/base price" value={base} onChange={v=>{setBase(v);setScenarios(all=>all.map((s,i)=>({...s,purchasePrice:mode==="price"?v+i*increment:v,overrides:{...s.overrides,apr:undefined,interestRate:undefined,lenderCredits:undefined,discountPointsPercent:undefined}})))}}/><Money label="Price increment" value={increment} onChange={v=>{setIncrement(v);if(mode==="price")setScenarios(all=>all.map((s,i)=>({...s,purchasePrice:base+i*v,overrides:{...s.overrides,apr:undefined}})))}}/></div><div className="bp-scenario-inputs">{scenarios.map((s,i)=><div key={s.id}><input className="bp-name" value={s.name} onChange={e=>setScenarios(a=>a.map((x,n)=>n===i?{...x,name:e.target.value}:x))}/>{mode==="price"?<Money label="Purchase price" value={s.purchasePrice} onChange={v=>setScenarios(a=>a.map((x,n)=>n===i?{...x,purchasePrice:v,overrides:{...x.overrides,apr:undefined}}:x))}/>:<><OptionalNumber label="Down payment" suffix="%" value={s.overrides.downPaymentPercent} onChange={v=>setOverride(i,"downPaymentPercent",v)}/><OptionalMoney label="Monthly MI" value={s.overrides.monthlyMortgageInsurance} onChange={v=>setOverride(i,"monthlyMortgageInsurance",v)}/></>}</div>)}</div></Section>
  <Section n="03" title="Loan"><div className="bp-grid four"><Text label="Borrower (optional)" value={shared.borrowerName} onChange={v=>setSharedValue("borrowerName",v)}/><label className="bp-field"><span>Loan program</span><select value={shared.loanProgram} onChange={e=>setSharedValue("loanProgram",e.target.value)}><option value="conventional">Conventional</option><option value="fha">FHA</option><option value="va">VA</option><option value="usda">USDA</option><option value="other">Other</option></select></label><NumberInput label="Default interest rate" suffix="%" value={shared.defaultInterestRate} onChange={v=>setSharedValue("defaultInterestRate",v)}/><NumberInput label="Loan term" suffix="years" value={shared.termYears} onChange={v=>setSharedValue("termYears",v)}/>{mode==="price"&&<><NumberInput label="Default down payment" suffix="%" value={shared.defaultDownPaymentPercent} onChange={v=>setSharedValue("defaultDownPaymentPercent",v)}/><Money label="Default monthly MI" value={shared.defaultMonthlyMortgageInsurance} onChange={v=>setSharedValue("defaultMonthlyMortgageInsurance",String(v))}/></>}</div></Section>
  <Section n="04" title="Monthly housing costs"><div className="bp-grid four"><Money label="Annual property taxes" value={shared.annualPropertyTaxes} onChange={v=>setSharedValue("annualPropertyTaxes",String(v))}/><Money label="Annual homeowners insurance" value={shared.annualHomeownersInsurance} onChange={v=>setSharedValue("annualHomeownersInsurance",String(v))}/><Money label="Monthly HOA" value={shared.monthlyHoa} onChange={v=>setSharedValue("monthlyHoa",String(v))}/></div><Inclusions value={inclusions} onChange={setInclusions}/></Section>
  <Section n="05" title="Costs & scenario pricing"><div className="bp-grid four"><Money label="Default closing costs" value={shared.defaultClosingCosts} onChange={v=>setSharedValue("defaultClosingCosts",String(v))}/><Money label="Prepaids & escrows" value={shared.prepaidEscrows} onChange={v=>setSharedValue("prepaidEscrows",String(v))}/><OptionalMoney label="Earnest money / deposit already paid" value={shared.earnestMoneyDeposit??undefined} onChange={v=>setSharedValue("earnestMoneyDeposit",v)}/><Money label="Default seller concessions" value={shared.defaultSellerConcessions} onChange={v=>setSharedValue("defaultSellerConcessions",String(v))}/></div><div className="bp-overrides"><span>Scenario pricing — APR is required for final export and is never calculated here.</span>{scenarios.map((s,i)=><details open key={s.id}><summary>{s.name}</summary><div className="bp-grid four"><OptionalNumber label="Interest rate" suffix="%" value={s.overrides.interestRate} onChange={v=>setOverride(i,"interestRate",v)}/><OptionalNumber label="Verified APR" suffix="%" value={s.overrides.apr} onChange={v=>setOverride(i,"apr",v)}/><OptionalNumber label="Discount points" suffix="%" value={s.overrides.discountPointsPercent} onChange={v=>setOverride(i,"discountPointsPercent",v)}/><OptionalMoney label="Lender credits" value={s.overrides.lenderCredits} onChange={v=>setOverride(i,"lenderCredits",v)}/><OptionalMoney label="Closing costs" value={s.overrides.closingCosts} onChange={v=>setOverride(i,"closingCosts",v)}/><OptionalMoney label="Seller concessions" value={s.overrides.sellerConcessions} onChange={v=>setOverride(i,"sellerConcessions",v)}/><OptionalMoney label="Financed upfront fee" value={s.overrides.financedUpfrontFee} onChange={v=>setOverride(i,"financedUpfrontFee",v)}/><OptionalMoney label="Verified total loan amount" value={s.overrides.totalLoanAmount} onChange={v=>setOverride(i,"totalLoanAmount",v)}/></div></details>)}</div></Section>
  <ComplianceSection disclosure={disclosure} setDisclosure={setDisclosure} status={status} setStatus={setStatus} rateAsOf={rateAsOf} setRateAsOf={setRateAsOf} approval={approval} setApproval={setApproval} errors={compliance.errors}/>
  <div className="bp-submit"><div><span>Starting estimated payment</span><strong>{usd.format(results[0].totalMonthlyHousingPayment)}<small>/mo</small></strong></div><button className="button primary large" onClick={()=>{save();setView("report")}}>Create review report →</button></div></section></div>:<Report mode={mode} shared={shared} results={results} differences={differences} disclosure={disclosure} inclusions={inclusions} status={status} rateAsOf={rateAsOf} exportAllowed={exportAllowed} onEdit={()=>setView("input")}/>}</main>;
}

function Report({mode,shared,results,differences,disclosure,inclusions,status,rateAsOf,exportAllowed,onEdit}:{mode:"price"|"downPayment";shared:BuyingPowerSharedAssumptions;results:ReturnType<typeof calculateScenario>[];differences:ReturnType<typeof calculateScenarioDifference>[];disclosure:DisclosureConfig;inclusions:PaymentInclusions;status:ReportStatus;rateAsOf:string;exportAllowed:boolean;onEdit:()=>void}){return <div className="bp-report-wrap"><div className="report-toolbar no-print"><button className="text-button" onClick={onEdit}>← Edit comparison</button><span>{exportAllowed?"Employer approval recorded · Export enabled":"Review copy · Export disabled"}</span></div><article className="bp-report"><header className="bp-report-hero"><div className="report-brand"><span className="brand-mark light">A</span><div>{disclosure.companyName}<small>Home buying power comparison</small></div></div><span>{status==="draft"?"DRAFT · ":""}Prepared {new Date().toLocaleDateString()}</span><div><p>{mode==="price"?"Purchase price comparison":"Down payment comparison"}</p><h1>Monthly payment and upfront cost estimates, side by side.</h1><h2>{rateAsOf?`Rates as of ${new Date(rateAsOf).toLocaleString()}`:"Rate timestamp required before export"}</h2></div></header>
<section className="bp-cards">{results.map((r,i)=><div className={i===1?"bp-card featured":"bp-card"} key={r.id}><span className="bp-card-name">{r.name}</span><h3>{mode==="price"?usd.format(r.purchasePrice):`${formatPercent(r.downPaymentPercent)} down`}</h3><div className="bp-big-metric"><span>Estimated total monthly payment</span><strong>{usd.format(r.totalMonthlyHousingPayment)}<small>/mo</small></strong><b>P&amp;I {usd.format(r.monthlyPrincipalAndInterest)}/mo for {shared.termYears*12} months</b><small>{formatPercent(r.interestRate)} fixed · {r.apr?`${formatPercent(r.apr)} APR`:"APR required"} · {formatPercent(r.downPaymentPercent)} down</small><small>{inclusions.propertyTaxes?`Taxes ${usd.format(r.monthlyTaxes)} · `:""}{inclusions.homeownersInsurance?`Insurance ${usd.format(r.monthlyInsurance)} · `:""}{inclusions.mortgageInsurance?`MI ${usd.format(r.monthlyMortgageInsurance)} · `:""}{inclusions.hoa?`HOA ${usd.format(r.monthlyHoa)}`:""}</small>{(!inclusions.propertyTaxes||!inclusions.homeownersInsurance)&&<em>Taxes and/or insurance are not included. Actual payment will be higher.</em>}<small>Taxes, insurance, MI, and HOA may change.</small></div><div className="bp-cash"><span>Estimated cash to close</span><strong>{usd.format(r.cashToClose)}</strong></div></div>)}</section>
<Visual results={results} mode={mode}/><section className="bp-report-section alt"><div className="eyebrow">Upfront costs</div><h2>Reconciled estimated cash to close</h2><Comparison rows={["Down payment","Closing costs","Prepaids & escrows","Discount points","Less applied seller concessions","Less applied lender credits","Less earnest money / deposit","Estimated cash to close"]} results={results} values={r=>[r.downPayment,r.closingCosts,r.prepaidEscrows,r.discountPoints,-r.sellerConcessionsApplied,-r.lenderCreditsApplied,-r.earnestMoneyDeposit,r.cashToClose]}/>{results.some(r=>r.unusedSellerConcessions>0||r.unusedLenderCredits>0)&&<div className="bp-warning">Some entered credits were not applied because modeled eligible costs were exhausted. Final eligibility and application must be verified.</div>}</section>
<section className="bp-report-section"><div className="eyebrow">Monthly payment</div><h2>Included payment components</h2><Comparison rows={["Principal & interest",...(inclusions.propertyTaxes?["Property taxes"]:[]),...(inclusions.homeownersInsurance?["Homeowners insurance"]:[]),...(inclusions.mortgageInsurance?["Mortgage insurance"]:[]),...(inclusions.hoa?["HOA"]:[]),"Total housing payment"]} results={results} values={r=>[r.monthlyPrincipalAndInterest,...(inclusions.propertyTaxes?[r.monthlyTaxes]:[]),...(inclusions.homeownersInsurance?[r.monthlyInsurance]:[]),...(inclusions.mortgageInsurance?[r.monthlyMortgageInsurance]:[]),...(inclusions.hoa?[r.monthlyHoa]:[]),r.totalMonthlyHousingPayment]}/></section>
<section className="bp-report-section bp-assumptions"><div><div className="eyebrow">Shared assumptions</div><h2>Inputs common to every scenario</h2></div><div className="bp-assumption-list"><span>Loan program<strong>{shared.loanProgram}</strong></span><span>Term<strong>{shared.termYears} years</strong></span><span>Default rate<strong>{formatPercent(shared.defaultInterestRate)}</strong></span><span>Property taxes<strong>{usd.format(shared.annualPropertyTaxes)}/yr</strong></span><span>Insurance<strong>{usd.format(shared.annualHomeownersInsurance)}/yr</strong></span></div></section>
<footer className="disclosure"><strong>Important disclosure</strong><p>{disclosure.customDisclosure||"Estimates are for educational comparison only and are not a commitment to lend, loan approval, or guarantee of terms. Rates, APR, payments, taxes, insurance, mortgage insurance, HOA, costs, and eligibility may change and require verification. No government-loan fee or program rule is inferred by this tool."}</p><div><span>{disclosure.loanOfficerName} · {disclosure.loanOfficerTitle} · NMLS {disclosure.loanOfficerNmlsId}</span><span>{disclosure.companyName} · Company NMLS {disclosure.companyNmlsId||"not entered"} · {disclosure.companyState} · {disclosure.companyLicenseType} {disclosure.companyStateLicenseNumber}</span>{status==="draft"&&<span>For compliance review before publication</span>}</div></footer></article></div>}

function ComplianceSection({disclosure,setDisclosure,status,setStatus,rateAsOf,setRateAsOf,approval,setApproval,errors}:{disclosure:DisclosureConfig;setDisclosure:React.Dispatch<React.SetStateAction<DisclosureConfig>>;status:ReportStatus;setStatus:(v:ReportStatus)=>void;rateAsOf:string;setRateAsOf:(v:string)=>void;approval:ApprovalRecord;setApproval:React.Dispatch<React.SetStateAction<ApprovalRecord>>;errors:string[]}){const d=(k:keyof DisclosureConfig,v:string)=>setDisclosure(x=>({...x,[k]:v}));const a=(k:keyof ApprovalRecord,v:string|boolean)=>setApproval(x=>({...x,[k]:v}));return <Section n="06" title="Publication / compliance"><div className="bp-mode">{(["draft","readyForCompliance","approved"] as ReportStatus[]).map(v=><button key={v} className={status===v?"on":""} onClick={()=>setStatus(v)}>{v==="draft"?"Draft":v==="readyForCompliance"?"Ready for compliance":"Approved"}</button>)}</div><div className="bp-grid four"><Text label="Loan officer" value={disclosure.loanOfficerName} onChange={v=>d("loanOfficerName",v)}/><Text label="LO NMLS ID" value={disclosure.loanOfficerNmlsId} onChange={v=>d("loanOfficerNmlsId",v)}/><Text label="Company" value={disclosure.companyName} onChange={v=>d("companyName",v)}/><Text label="Company NMLS ID" value={disclosure.companyNmlsId} onChange={v=>d("companyNmlsId",v)}/><Text label="State license type" value={disclosure.companyLicenseType} onChange={v=>d("companyLicenseType",v)}/><Text label="State license number" value={disclosure.companyStateLicenseNumber} onChange={v=>d("companyStateLicenseNumber",v)}/><Text label="Licensed state" value={disclosure.companyState} onChange={v=>d("companyState",v)}/><Text label="Rate as of" type="datetime-local" value={rateAsOf} onChange={setRateAsOf}/></div><div className="bp-grid four"><label className="bp-field"><span>Employer approval received</span><input type="checkbox" checked={approval.approvalConfirmed} onChange={e=>a("approvalConfirmed",e.target.checked)}/></label><Text label="Approved by" value={approval.approvedBy} onChange={v=>a("approvedBy",v)}/><Text label="Approved at" type="datetime-local" value={approval.approvedAt} onChange={v=>a("approvedAt",v)}/><Text label="Approval reference / notes" value={approval.approvalReference} onChange={v=>a("approvalReference",v)}/></div>{status!=="draft"&&errors.length>0&&<div className="bp-validation"><strong>Final export remains blocked:</strong><ul>{errors.map(e=><li key={e}>{e}</li>)}</ul></div>}</Section>}
function Visual({results,mode}:{results:ReturnType<typeof calculateScenario>[];mode:"price"|"downPayment"}){const max=Math.max(...results.map(r=>r.totalMonthlyHousingPayment),1);return <section className="bp-visuals"><div><span className="eyebrow">Monthly payment</span><h2>Estimated payment at each {mode==="price"?"price":"down payment"}</h2>{results.map((r,i)=><div className="bp-bar-row" key={r.id}><span>{r.name}</span><div><i style={{width:`${r.totalMonthlyHousingPayment/max*100}%`}} className={`tone-${i}`}/></div><strong>{usd.format(r.totalMonthlyHousingPayment)}</strong></div>)}</div></section>}
function Comparison({rows,results,values}:{rows:string[];results:ReturnType<typeof calculateScenario>[];values:(r:ReturnType<typeof calculateScenario>)=>number[]}){return <div className="bp-comparison"><div className="bp-table-head"><span></span>{results.map(r=><strong key={r.id}>{r.name}</strong>)}</div>{rows.map((row,i)=><div className={i===rows.length-1?"total":""} key={row}><span>{row}</span>{results.map(r=><strong key={r.id}>{usd.format(values(r)[i])}</strong>)}</div>)}</div>}
function Section({n,title,children}:{n:string;title:string;children:React.ReactNode}){return <section className="bp-input-section"><h3><b>{n}</b> {title}</h3>{children}</section>}
function Text({label,value,onChange,type="text"}:{label:string;value:string;onChange:(v:string)=>void;type?:string}){return <label className="bp-field"><span>{label}</span><input type={type} value={value} onChange={e=>onChange(e.target.value)}/></label>}
function Money({label,value,onChange}:{label:string;value:number;onChange:(v:number)=>void}){return <label className="bp-field"><span>{label}</span><div className="bp-money"><span>$</span><input type="number" min="0" value={value||""} placeholder="Unknown" onChange={e=>onChange(Number(e.target.value))}/></div></label>}
function OptionalMoney({label,value,onChange}:{label:string;value:number|undefined;onChange:(v:string)=>void}){return <label className="bp-field"><span>{label}</span><div className="bp-money"><span>$</span><input type="number" min="0" value={value??""} placeholder="Inherit / unknown" onChange={e=>onChange(e.target.value)}/></div></label>}
function NumberInput({label,value,onChange,suffix}:{label:string;value:number;onChange:(v:string)=>void;suffix:string}){return <label className="bp-field"><span>{label}</span><div className="bp-number"><input type="number" min="0" step="0.001" value={value||""} placeholder="Unknown" onChange={e=>onChange(e.target.value)}/><span>{suffix}</span></div></label>}
function OptionalNumber({label,value,onChange,suffix}:{label:string;value:number|undefined;onChange:(v:string)=>void;suffix:string}){return <label className="bp-field"><span>{label}</span><div className="bp-number"><input type="number" min="0" step="0.001" value={value??""} placeholder="Inherit / unknown" onChange={e=>onChange(e.target.value)}/><span>{suffix}</span></div></label>}
function Inclusions({value,onChange}:{value:PaymentInclusions;onChange:React.Dispatch<React.SetStateAction<PaymentInclusions>>}){return <div className="bp-inclusion-options"><span>Advertised payment includes:</span>{Object.entries({propertyTaxes:"Property taxes",homeownersInsurance:"Homeowners insurance",mortgageInsurance:"Mortgage insurance",hoa:"HOA"}).map(([k,l])=><label key={k}><input type="checkbox" checked={value[k as keyof PaymentInclusions]} onChange={e=>onChange(v=>({...v,[k]:e.target.checked}))}/>{l}</label>)}</div>}
