import type { ApprovalRecord, BuyingPowerScenarioInput, BuyingPowerSharedAssumptions, DisclosureConfig, PaymentInclusions, ReportStatus } from "./types";
export const BUYING_POWER_STORAGE_KEY = "bhl-buying-power";
export const BUYING_POWER_STORAGE_VERSION = 2;
export function scenariosForMode(base: number, mode: "price" | "downPayment"): BuyingPowerScenarioInput[] { return [0,1,2].map((i)=>({id:String.fromCharCode(97+i),name:mode==="price"?`Scenario ${String.fromCharCode(65+i)}`:`${[5,10,20][i]}% Down`,purchasePrice:mode==="price"?base+i*10000:base,notes:"",overrides:mode==="downPayment"?{downPaymentPercent:[5,10,20][i]}:{}})); }
export interface BuyingPowerSavedState { version: 2; shared: BuyingPowerSharedAssumptions; scenarios: BuyingPowerScenarioInput[]; base: number; increment: number; compareMode: "price" | "downPayment"; disclosure: DisclosureConfig; inclusions: PaymentInclusions; reportStatus: ReportStatus; rateAsOf: string; approval: ApprovalRecord; }
export function migrateBuyingPowerState(raw: unknown, defaults: Omit<BuyingPowerSavedState, "version">): BuyingPowerSavedState {
  const old = (raw && typeof raw === "object" ? raw : {}) as Record<string, any>;
  const legacy = old.shared ?? {};
  const shared = { ...defaults.shared, ...legacy, defaultInterestRate: legacy.defaultInterestRate ?? legacy.interestRate ?? defaults.shared.defaultInterestRate, defaultDownPaymentPercent: legacy.defaultDownPaymentPercent ?? legacy.downPaymentPercent ?? defaults.shared.defaultDownPaymentPercent, defaultMonthlyMortgageInsurance: legacy.defaultMonthlyMortgageInsurance ?? legacy.monthlyMortgageInsurance ?? defaults.shared.defaultMonthlyMortgageInsurance, defaultClosingCosts: legacy.defaultClosingCosts ?? legacy.closingCosts ?? defaults.shared.defaultClosingCosts, defaultSellerConcessions: legacy.defaultSellerConcessions ?? legacy.sellerConcessions ?? defaults.shared.defaultSellerConcessions, defaultLenderCredits: legacy.defaultLenderCredits ?? legacy.lenderCredits ?? defaults.shared.defaultLenderCredits, defaultDiscountPointsPercent: legacy.defaultDiscountPointsPercent ?? legacy.discountPointsPercent ?? defaults.shared.defaultDiscountPointsPercent };
  delete shared.apr; delete shared.interestRate; delete shared.downPaymentPercent; delete shared.monthlyMortgageInsurance; delete shared.closingCosts; delete shared.sellerConcessions; delete shared.lenderCredits; delete shared.discountPointsPercent;
  const scenarios = (old.scenarios ?? defaults.scenarios).map((s: BuyingPowerScenarioInput) => ({ ...s, overrides: Object.fromEntries(Object.entries(s.overrides ?? {}).filter(([key]) => key !== "downPaymentAmount")) }));
  return { ...defaults, ...old, version: 2, shared, scenarios, approval: old.approval ?? defaults.approval, reportStatus: old.reportStatus === "clientReady" ? "readyForCompliance" : old.reportStatus ?? defaults.reportStatus };
}
