import type { LoanProgram } from "@/domain/loan";

export type InputOrigin = "manual" | "inherited" | "overridden" | "calculated" | "imported";
export type ReportStatus = "draft" | "readyForCompliance" | "approved";
export interface ApprovalRecord { approvalConfirmed: boolean; approvedBy: string; approvedAt: string; approvalReference: string; }
export interface DisclosureConfig { loanOfficerName: string; loanOfficerTitle: string; loanOfficerNmlsId: string; companyName: string; companyNmlsId: string; companyState: string; companyLicenseType: string; companyStateLicenseNumber: string; customDisclosure: string; }
export interface PaymentInclusions { propertyTaxes: boolean; homeownersInsurance: boolean; mortgageInsurance: boolean; hoa: boolean; }
export interface BuyingPowerSharedAssumptions { borrowerName: string; loanProgram: LoanProgram; termYears: number; defaultInterestRate: number; defaultDownPaymentPercent: number; annualPropertyTaxes: number; annualHomeownersInsurance: number; defaultMonthlyMortgageInsurance: number; monthlyHoa: number; defaultClosingCosts: number; defaultSellerConcessions: number; defaultDiscountPointsPercent: number; defaultLenderCredits: number; prepaidEscrows: number; earnestMoneyDeposit: number | null; targetMonthlyPayment: number | null; holdingPeriodYears: number; }
export interface ScenarioOverrides { interestRate?: number; apr?: number; downPaymentPercent?: number; monthlyMortgageInsurance?: number; closingCosts?: number; sellerConcessions?: number; lenderCredits?: number; discountPointsPercent?: number; financedUpfrontFee?: number; totalLoanAmount?: number; earnestMoneyDeposit?: number; }
export interface BuyingPowerScenarioInput { id: string; name: string; purchasePrice: number; notes: string; overrides: ScenarioOverrides; }
export interface BuyingPowerScenarioResult { id: string; name: string; notes: string; purchasePrice: number; downPaymentPercent: number; downPayment: number; baseLoanAmount: number; financedUpfrontFee: number | null; totalLoanAmount: number; ltvPercent: number | null; interestRate: number; apr: number | null; monthlyPrincipalAndInterest: number; monthlyTaxes: number; monthlyInsurance: number; monthlyMortgageInsurance: number; monthlyHoa: number; totalMonthlyHousingPayment: number; closingCosts: number; prepaidEscrows: number; discountPoints: number; sellerConcessionsEntered: number; sellerConcessionsApplied: number; unusedSellerConcessions: number; lenderCreditsEntered: number; lenderCreditsApplied: number; unusedLenderCredits: number; earnestMoneyDeposit: number; cashToClose: number; remainingBalanceAtHoldingPeriod: number; principalPaidAtHoldingPeriod: number; interestPaidAtHoldingPeriod: number; targetPaymentDifference: number | null; origins: Record<string, InputOrigin>; }
export interface ScenarioDifference { purchasePrice: number; loanAmount: number; monthlyPayment: number; cashToClose: number; }
